name: Quality Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code_check:
    name: Elinting
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm i -D typescript jest ts-jest @types/jest eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
      - name: Run EsLinter
        run: npm run lint:cli
      - name: Fix lint error
        if: ${{ failure() }}
        run: echo "npm run lint-and-fix"

  sanitize:
    name: Check for forbidden words
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the forbidden words scan
        uses: dell/common-github-actions/code-sanitizer@main
        with:
          args: /github/workspace
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install jq
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm i -D typescript jest ts-jest @types/jest
      - name: Run Test
        run: npm run test:cli
      - name: Check coverage
        run: |
          total=$(jq '(.total.lines.pct + .total.statements.pct + .total.functions.pct  + .total.branches.pct)/4' coverage/coverage-summary.json)
          TOTAL_APPROX=$(jq -n "$total | floor")
          if [ ${TOTAL_APPROX} -lt ${THRESHOLD} ]
          then
            echo Coverage: ${TOTAL_APPROX}%, but threshold is set to ${THRESHOLD}%
            exit 1
          fi
        env:
          THRESHOLD: 60

  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
  ts_security_scan:
    name: TypeScript security
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
